# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tree_search_rcpp <- function(X, Y, depth, split_step, min_node_size, max_treatment_size) {
    .Call('_constrainedpolicytree_tree_search_rcpp', PACKAGE = 'constrainedpolicytree', X, Y, depth, split_step, min_node_size, max_treatment_size)
}

tree_search_rcpp_predict <- function(tree_array, X) {
    .Call('_constrainedpolicytree_tree_search_rcpp_predict', PACKAGE = 'constrainedpolicytree', tree_array, X)
}

